//HintName: TransferSyntax.Generated.cs
// <auto-generated />
#nullable enable

namespace SharpDicom.Data
{
    /// <summary>
    /// DICOM transfer syntax definitions - generated from NEMA Part 6 standard XML.
    /// </summary>
    public static partial class TransferSyntaxes
    {
        /// <summary>
        /// Implicit VR Little Endian
        /// </summary>
        public static readonly DicomUID ImplicitVRLittleEndian = DicomUIDs.ImplicitVRLittleEndian;
        /// <summary>
        /// Explicit VR Little Endian
        /// </summary>
        public static readonly DicomUID ExplicitVRLittleEndian = DicomUIDs.ExplicitVRLittleEndian;
    }
}
