//HintName: DicomTag.Generated.cs
// <auto-generated />
#nullable enable

namespace SharpDicom.Data
{
    /// <summary>
    /// DICOM tag dictionary - generated from NEMA Part 6 standard XML.
    /// </summary>
    public static partial class DicomTags
    {
        // Group 0008
        /// <summary>
        /// Data Set Subtype (0008,0041) - LO - VM:1 [RETIRED]
        /// </summary>
        [System.Obsolete("This tag is retired in the DICOM standard.")]
        public static readonly DicomTag DataSetSubtype = new DicomTag(0x0008, 0x0041);
    }
}
