//HintName: DicomTag.Generated.cs
// <auto-generated />
#nullable enable

namespace SharpDicom.Data
{
    /// <summary>
    /// DICOM tag dictionary - generated from NEMA Part 6 standard XML.
    /// </summary>
    public static partial class DicomTags
    {
        // Group 5000
        /// <summary>
        /// Number of Points in ROI (5000,0010) - US - VM:1
        /// </summary>
        public static readonly DicomTag NumberOfPointsInROI = new DicomTag(0x5000, 0x0010);
    }
}
