//HintName: DicomTag.Generated.cs
// <auto-generated />
#nullable enable

namespace SharpDicom.Data
{
    /// <summary>
    /// DICOM tag dictionary - generated from NEMA Part 6 standard XML.
    /// </summary>
    public static partial class DicomTags
    {
        // Group 0008
        /// <summary>
        /// Study Date (0008,0020) - DA - VM:1
        /// </summary>
        public static readonly DicomTag StudyDate = new DicomTag(0x0008, 0x0020);
    }
}
