//HintName: DicomUID.Generated.cs
// <auto-generated />
#nullable enable

namespace SharpDicom.Data
{
    /// <summary>
    /// DICOM UID dictionary - generated from NEMA Part 6 standard XML.
    /// </summary>
    public static partial class DicomUIDs
    {
        // Transfer Syntax
        /// <summary>
        /// Implicit VR Little Endian - Transfer Syntax
        /// </summary>
        public static readonly DicomUID ImplicitVRLittleEndian = new DicomUID("1.2.840.10008.1.2");
        /// <summary>
        /// Explicit VR Little Endian - Transfer Syntax
        /// </summary>
        public static readonly DicomUID ExplicitVRLittleEndian = new DicomUID("1.2.840.10008.1.2.1");
    }
}
