//HintName: DicomTag.Generated.cs
// <auto-generated />
#nullable enable

namespace SharpDicom.Data
{
    /// <summary>
    /// DICOM tag dictionary - generated from NEMA Part 6 standard XML.
    /// </summary>
    public static partial class DicomTags
    {
        // Group 0010
        /// <summary>
        /// Patient ID (0010,0020) - LO - VM:1
        /// </summary>
        public static readonly DicomTag PatientID = new DicomTag(0x0010, 0x0020);
    }
}
