//HintName: DicomTag.Generated.cs
// <auto-generated />
#nullable enable

namespace SharpDicom.Data
{
    /// <summary>
    /// DICOM tag dictionary - generated from NEMA Part 6 standard XML.
    /// </summary>
    public static partial class DicomTags
    {
        // Group 0028
        /// <summary>
        /// Smallest Image Pixel Value (0028,0106) - US/SS - VM:1
        /// </summary>
        public static readonly DicomTag SmallestImagePixelValue = new DicomTag(0x0028, 0x0106);
    }
}
