//HintName: DicomDictionary.Generated.cs
// <auto-generated />
#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
#if NET8_0_OR_GREATER
using System.Collections.Frozen;
#endif

namespace SharpDicom.Data
{
    /// <summary>
    /// Generated DICOM dictionary data - generated from NEMA Part 6 standard XML.
    /// </summary>
    internal static class GeneratedDictionaryData
    {
        private static readonly DicomTagEntry[] s_tagEntries = new[]
        {
            new DicomTagEntry(0x0008, 0x0020, "StudyDate", "Study Date", new[] { "DA" }, "1", false),
        };

#if NET8_0_OR_GREATER
        private static readonly FrozenDictionary<uint, DicomTagEntry> s_tagByValue =
            s_tagEntries.ToFrozenDictionary(e => ((uint)e.Group << 16) | e.Element);

        private static readonly FrozenDictionary<string, DicomTagEntry> s_tagByKeyword =
            s_tagEntries.ToFrozenDictionary(e => e.Keyword, StringComparer.OrdinalIgnoreCase);
#else
        private static readonly Dictionary<uint, DicomTagEntry> s_tagByValue =
            s_tagEntries.ToDictionary(e => ((uint)e.Group << 16) | e.Element);

        private static readonly Dictionary<string, DicomTagEntry> s_tagByKeyword =
            s_tagEntries.ToDictionary(e => e.Keyword, StringComparer.OrdinalIgnoreCase);
#endif

        private static readonly DicomUIDEntry[] s_uidEntries = new[]
        {
            new DicomUIDEntry("1.2.840.10008.5.1.4.1.1.2", "CTImageStorage", "CT Image Storage", "SOP Class", false),
        };

#if NET8_0_OR_GREATER
        private static readonly FrozenDictionary<string, DicomUIDEntry> s_uidByValue =
            s_uidEntries.ToFrozenDictionary(e => e.Value);

        private static readonly FrozenDictionary<string, DicomUIDEntry> s_uidByKeyword =
            s_uidEntries.ToFrozenDictionary(e => e.Keyword);
#else
        private static readonly Dictionary<string, DicomUIDEntry> s_uidByValue =
            s_uidEntries.ToDictionary(e => e.Value);

        private static readonly Dictionary<string, DicomUIDEntry> s_uidByKeyword =
            s_uidEntries.ToDictionary(e => e.Keyword);
#endif

        /// <summary>
        /// Looks up a tag entry by group and element.
        /// </summary>
        public static DicomTagEntry? GetTag(ushort group, ushort element)
        {
            var value = ((uint)group << 16) | element;
            return s_tagByValue.TryGetValue(value, out var entry) ? entry : null;
        }

        /// <summary>
        /// Looks up a tag entry by keyword.
        /// </summary>
        public static DicomTagEntry? GetTag(string keyword)
        {
            return s_tagByKeyword.TryGetValue(keyword, out var entry) ? entry : null;
        }

        /// <summary>
        /// Looks up a UID entry by value.
        /// </summary>
        public static DicomUIDEntry? GetUID(string value)
        {
            return s_uidByValue.TryGetValue(value, out var entry) ? entry : null;
        }

        /// <summary>
        /// Looks up a UID entry by keyword.
        /// </summary>
        public static DicomUIDEntry? GetUIDByKeyword(string keyword)
        {
            return s_uidByKeyword.TryGetValue(keyword, out var entry) ? entry : null;
        }
    }

    /// <summary>
    /// Represents a DICOM tag dictionary entry.
    /// </summary>
    public readonly record struct DicomTagEntry(
        ushort Group,
        ushort Element,
        string Keyword,
        string Name,
        string[] VRs,
        string VM,
        bool IsRetired);

    /// <summary>
    /// Represents a DICOM UID dictionary entry.
    /// </summary>
    public readonly record struct DicomUIDEntry(
        string Value,
        string Keyword,
        string Name,
        string Type,
        bool IsRetired);
}
