//HintName: DicomUID.Generated.cs
// <auto-generated />
#nullable enable

namespace SharpDicom.Data
{
    /// <summary>
    /// DICOM UID dictionary - generated from NEMA Part 6 standard XML.
    /// </summary>
    public static partial class DicomUIDs
    {
        // SOP Class
        /// <summary>
        /// CT Image Storage - SOP Class
        /// </summary>
        public static readonly DicomUID CTImageStorage = new DicomUID("1.2.840.10008.5.1.4.1.1.2");
    }
}
