<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="SharpDicom.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SharpDicom\SharpDicom.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Tomlyn" />
  </ItemGroup>
</Project>
