<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="SharpDicom.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SharpDicom\SharpDicom.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Tomlyn" />
    <PackageReference Include="PublishAotCross" />
    <PackageReference Include="PublishAotCrossXWin" />
  </ItemGroup>
</Project>
