using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Text;

namespace SharpDicom.Generators.Emitters
{
    /// <summary>
    /// Generates C# source code for de-identification action tables from PS3.15 data.
    /// </summary>
    internal static class DeidentificationTableEmitter
    {
        /// <summary>
        /// Emits C# source code for DeidentificationActionTable.Generated.cs.
        /// </summary>
        /// <param name="actions">The confidentiality action definitions from Part 15.</param>
        /// <returns>Generated C# source code.</returns>
        public static string Emit(ImmutableArray<Parsing.ConfidentialityActionDefinition> actions)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("#if NET8_0_OR_GREATER");
            sb.AppendLine("using System.Collections.Frozen;");
            sb.AppendLine("#endif");
            sb.AppendLine("using SharpDicom.Data;");
            sb.AppendLine();
            sb.AppendLine("namespace SharpDicom.Deidentification");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Generated de-identification action table from DICOM PS3.15 Table E.1-1.");
            sb.AppendLine("    /// Maps (DicomTag, DeidentificationProfile) to DeidentificationAction.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static partial class DeidentificationActionTable");
            sb.AppendLine("    {");

            // Generate dictionary initialization
            sb.AppendLine("#if NET8_0_OR_GREATER");
            sb.AppendLine("        private static readonly FrozenDictionary<uint, ActionEntry> s_actions =");
            sb.AppendLine("            new Dictionary<uint, ActionEntry>");
            sb.AppendLine("#else");
            sb.AppendLine("        private static readonly Dictionary<uint, ActionEntry> s_actions =");
            sb.AppendLine("            new Dictionary<uint, ActionEntry>");
            sb.AppendLine("#endif");
            sb.AppendLine("            {");

            // Deduplicate by tag value, preferring entries with more complete profiles
            var seenTags = new HashSet<uint>();
            foreach (var action in actions)
            {
                var tagValue = ((uint)action.Group << 16) | action.Element;
                if (!seenTags.Add(tagValue))
                {
                    continue; // Skip duplicate tags
                }

                sb.Append("                // ");
                sb.Append(action.Name);
                sb.Append(" (");
                sb.Append(action.Group.ToString("X4", CultureInfo.InvariantCulture));
                sb.Append(',');
                sb.Append(action.Element.ToString("X4", CultureInfo.InvariantCulture));
                sb.AppendLine(")");

                sb.Append("                [0x");
                sb.Append(tagValue.ToString("X8", CultureInfo.InvariantCulture));
                sb.AppendLine("] = new ActionEntry(");

                // Emit all 11 action values using fully qualified enum names
                sb.Append("                    ");
                sb.Append(MapToEnumValue(action.BasicAction));
                sb.AppendLine(",");

                sb.Append("                    ");
                sb.Append(MapToEnumValue(action.RetainSafePrivateAction));
                sb.AppendLine(",");

                sb.Append("                    ");
                sb.Append(MapToEnumValue(action.RetainUidsAction));
                sb.AppendLine(",");

                sb.Append("                    ");
                sb.Append(MapToEnumValue(action.RetainDeviceIdentityAction));
                sb.AppendLine(",");

                sb.Append("                    ");
                sb.Append(MapToEnumValue(action.RetainInstitutionIdentityAction));
                sb.AppendLine(",");

                sb.Append("                    ");
                sb.Append(MapToEnumValue(action.RetainPatientCharacteristicsAction));
                sb.AppendLine(",");

                sb.Append("                    ");
                sb.Append(MapToEnumValue(action.RetainLongFullDatesAction));
                sb.AppendLine(",");

                sb.Append("                    ");
                sb.Append(MapToEnumValue(action.RetainLongModifDatesAction));
                sb.AppendLine(",");

                sb.Append("                    ");
                sb.Append(MapToEnumValue(action.CleanDescAction));
                sb.AppendLine(",");

                sb.Append("                    ");
                sb.Append(MapToEnumValue(action.CleanStructuredContentAction));
                sb.AppendLine(",");

                sb.Append("                    ");
                sb.Append(MapToEnumValue(action.CleanGraphAction));
                sb.AppendLine("),");
            }

            sb.AppendLine("            }");
            sb.AppendLine("#if NET8_0_OR_GREATER");
            sb.AppendLine("            .ToFrozenDictionary();");
            sb.AppendLine("#else");
            sb.AppendLine("            ;");
            sb.AppendLine("#endif");
            sb.AppendLine();

            // Generate GetAction method
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Gets the de-identification action for a tag and profile combination.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <param name=\"tag\">The DICOM tag.</param>");
            sb.AppendLine("        /// <param name=\"profile\">The de-identification profile (with options).</param>");
            sb.AppendLine("        /// <returns>The action to take for the tag.</returns>");
            sb.AppendLine("        public static DeidentificationAction GetAction(DicomTag tag, DeidentificationProfile profile)");
            sb.AppendLine("        {");
            sb.AppendLine("            var tagValue = ((uint)tag.Group << 16) | tag.Element;");
            sb.AppendLine("            if (!s_actions.TryGetValue(tagValue, out var entry))");
            sb.AppendLine("            {");
            sb.AppendLine("                // Unknown tags default to Remove for safety");
            sb.AppendLine("                return DeidentificationAction.Remove;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            return entry.GetAction(profile);");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Generate GetBasicAction method for simple lookup
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Gets the de-identification action for a tag using only the Basic profile.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <param name=\"tag\">The DICOM tag.</param>");
            sb.AppendLine("        /// <returns>The action to take for the tag.</returns>");
            sb.AppendLine("        public static DeidentificationAction GetBasicAction(DicomTag tag)");
            sb.AppendLine("        {");
            sb.AppendLine("            return GetAction(tag, DeidentificationProfile.Basic);");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Generate TryGetEntry method
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Tries to get the action entry for a tag.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <param name=\"tag\">The DICOM tag.</param>");
            sb.AppendLine("        /// <param name=\"entry\">The action entry if found.</param>");
            sb.AppendLine("        /// <returns>True if the tag is in the de-identification table.</returns>");
            sb.AppendLine("        public static bool TryGetEntry(DicomTag tag, out ActionEntry entry)");
            sb.AppendLine("        {");
            sb.AppendLine("            var tagValue = ((uint)tag.Group << 16) | tag.Element;");
            sb.AppendLine("            return s_actions.TryGetValue(tagValue, out entry);");
            sb.AppendLine("        }");

            sb.AppendLine("    }");
            sb.AppendLine();

            // Generate ActionEntry struct
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Represents the de-identification actions for a single tag across all profiles and options.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public readonly record struct ActionEntry(");
            sb.AppendLine("        DeidentificationAction Basic,");
            sb.AppendLine("        DeidentificationAction RetainSafePrivate,");
            sb.AppendLine("        DeidentificationAction RetainUIDs,");
            sb.AppendLine("        DeidentificationAction RetainDeviceIdentity,");
            sb.AppendLine("        DeidentificationAction RetainInstitutionIdentity,");
            sb.AppendLine("        DeidentificationAction RetainPatientCharacteristics,");
            sb.AppendLine("        DeidentificationAction RetainLongFullDates,");
            sb.AppendLine("        DeidentificationAction RetainLongModifDates,");
            sb.AppendLine("        DeidentificationAction CleanDescriptors,");
            sb.AppendLine("        DeidentificationAction CleanStructuredContent,");
            sb.AppendLine("        DeidentificationAction CleanGraphics)");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Gets the action for a profile, taking into account option flags.");
            sb.AppendLine("        /// Options override the Basic profile action when enabled.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public DeidentificationAction GetAction(DeidentificationProfile profile)");
            sb.AppendLine("        {");
            sb.AppendLine("            // Option flags override Basic profile when set");
            sb.AppendLine("            // Check options in order of precedence (most restrictive first)");
            sb.AppendLine();
            sb.AppendLine("            // Clean options - more restrictive (remove/clean more)");
            sb.AppendLine("            if ((profile & DeidentificationProfile.CleanGraphics) != 0 && CleanGraphics != DeidentificationAction.None)");
            sb.AppendLine("                return CleanGraphics;");
            sb.AppendLine();
            sb.AppendLine("            if ((profile & DeidentificationProfile.CleanStructuredContent) != 0 && CleanStructuredContent != DeidentificationAction.None)");
            sb.AppendLine("                return CleanStructuredContent;");
            sb.AppendLine();
            sb.AppendLine("            if ((profile & DeidentificationProfile.CleanDescriptors) != 0 && CleanDescriptors != DeidentificationAction.None)");
            sb.AppendLine("                return CleanDescriptors;");
            sb.AppendLine();
            sb.AppendLine("            // Retain options - less restrictive (keep more)");
            sb.AppendLine("            if ((profile & DeidentificationProfile.RetainLongitudinalFullDates) != 0 && RetainLongFullDates != DeidentificationAction.None)");
            sb.AppendLine("                return RetainLongFullDates;");
            sb.AppendLine();
            sb.AppendLine("            if ((profile & DeidentificationProfile.RetainLongitudinalModifiedDates) != 0 && RetainLongModifDates != DeidentificationAction.None)");
            sb.AppendLine("                return RetainLongModifDates;");
            sb.AppendLine();
            sb.AppendLine("            if ((profile & DeidentificationProfile.RetainPatientCharacteristics) != 0 && RetainPatientCharacteristics != DeidentificationAction.None)");
            sb.AppendLine("                return RetainPatientCharacteristics;");
            sb.AppendLine();
            sb.AppendLine("            if ((profile & DeidentificationProfile.RetainDeviceIdentity) != 0 && RetainDeviceIdentity != DeidentificationAction.None)");
            sb.AppendLine("                return RetainDeviceIdentity;");
            sb.AppendLine();
            sb.AppendLine("            if ((profile & DeidentificationProfile.RetainInstitutionIdentity) != 0 && RetainInstitutionIdentity != DeidentificationAction.None)");
            sb.AppendLine("                return RetainInstitutionIdentity;");
            sb.AppendLine();
            sb.AppendLine("            if ((profile & DeidentificationProfile.RetainUIDs) != 0 && RetainUIDs != DeidentificationAction.None)");
            sb.AppendLine("                return RetainUIDs;");
            sb.AppendLine();
            sb.AppendLine("            if ((profile & DeidentificationProfile.RetainSafePrivate) != 0 && RetainSafePrivate != DeidentificationAction.None)");
            sb.AppendLine("                return RetainSafePrivate;");
            sb.AppendLine();
            sb.AppendLine("            // Fall back to Basic profile action");
            sb.AppendLine("            return Basic;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// Maps an action code string to a fully qualified DeidentificationAction enum value.
        /// </summary>
        private static string MapToEnumValue(string actionCode)
        {
            if (string.IsNullOrEmpty(actionCode))
            {
                return "DeidentificationAction.None";
            }

            // Handle compound codes - take the first action as the primary
            // X/Z -> Remove (prefer removal over zero)
            // Z/D -> Zero (prefer zero over dummy)
            // X/D -> Remove (prefer removal over dummy)
            // X/Z/D -> Remove
            // X/Z/U -> Remove (for non-UID contexts)
            var normalizedCode = actionCode.Trim().ToUpperInvariant();

            // Extract primary action (before any /)
            var primaryCode = normalizedCode;
            var slashIndex = normalizedCode.IndexOf('/');
            if (slashIndex > 0)
            {
                primaryCode = normalizedCode.Substring(0, slashIndex);
            }

            return primaryCode switch
            {
                "D" => "DeidentificationAction.Dummy",
                "Z" => "DeidentificationAction.Zero",
                "X" => "DeidentificationAction.Remove",
                "K" => "DeidentificationAction.Keep",
                "C" => "DeidentificationAction.Clean",
                "U" => "DeidentificationAction.UidRemap",
                _ => "DeidentificationAction.None"
            };
        }
    }
}
