using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using SharpDicom.Generators.Parsing;

namespace SharpDicom.Generators.Emitters
{
    /// <summary>
    /// Generates C# source code for de-identification profile tables.
    /// </summary>
    internal static class DeidentificationEmitter
    {
        /// <summary>
        /// Emits C# source code for DeidentificationProfiles.Generated.cs.
        /// </summary>
        /// <param name="actions">The de-identification action definitions.</param>
        /// <returns>Generated C# source code.</returns>
        public static string Emit(ImmutableArray<DeidentificationActionDefinition> actions)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using SharpDicom.Data;");
            sb.AppendLine("#if NET8_0_OR_GREATER");
            sb.AppendLine("using System.Collections.Frozen;");
            sb.AppendLine("#endif");
            sb.AppendLine();
            sb.AppendLine("namespace SharpDicom.Deidentification");
            sb.AppendLine("{");

            // Generate DeidentificationAction enum
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Action codes from PS3.15 Table E.1-1a for de-identification.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public enum DeidentificationAction");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>Keep unchanged (K).</summary>");
            sb.AppendLine("        Keep,");
            sb.AppendLine("        /// <summary>Remove attribute (X).</summary>");
            sb.AppendLine("        Remove,");
            sb.AppendLine("        /// <summary>Replace with zero-length or dummy (Z).</summary>");
            sb.AppendLine("        ZeroOrDummy,");
            sb.AppendLine("        /// <summary>Replace with non-zero dummy (D).</summary>");
            sb.AppendLine("        Dummy,");
            sb.AppendLine("        /// <summary>Clean - replace with safe similar meaning (C).</summary>");
            sb.AppendLine("        Clean,");
            sb.AppendLine("        /// <summary>Replace with consistent UID (U).</summary>");
            sb.AppendLine("        RemapUid,");
            sb.AppendLine("        /// <summary>Z unless D required for Type 2 vs Type 1 (Z/D).</summary>");
            sb.AppendLine("        ZeroOrDummyConditional,");
            sb.AppendLine("        /// <summary>X unless Z required for Type 3 vs Type 2 (X/Z).</summary>");
            sb.AppendLine("        RemoveOrZeroConditional,");
            sb.AppendLine("        /// <summary>X unless D required for Type 3 vs Type 1 (X/D).</summary>");
            sb.AppendLine("        RemoveOrDummyConditional,");
            sb.AppendLine("        /// <summary>X unless Z or D required (X/Z/D).</summary>");
            sb.AppendLine("        RemoveOrZeroOrDummyConditional,");
            sb.AppendLine("        /// <summary>X unless Z or U required for UID sequences (X/Z/U*).</summary>");
            sb.AppendLine("        RemoveOrZeroOrUidConditional");
            sb.AppendLine("    }");
            sb.AppendLine();

            // Generate DeidentificationProfileOption flags enum
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Profile options for de-identification from PS3.15.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [Flags]");
            sb.AppendLine("    public enum DeidentificationProfileOption");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>No additional options.</summary>");
            sb.AppendLine("        None = 0,");
            sb.AppendLine("        /// <summary>Retain Safe Private Option.</summary>");
            sb.AppendLine("        RetainSafePrivate = 1 << 0,");
            sb.AppendLine("        /// <summary>Retain UIDs Option.</summary>");
            sb.AppendLine("        RetainUIDs = 1 << 1,");
            sb.AppendLine("        /// <summary>Retain Device Identity Option.</summary>");
            sb.AppendLine("        RetainDeviceIdentity = 1 << 2,");
            sb.AppendLine("        /// <summary>Retain Institution Identity Option.</summary>");
            sb.AppendLine("        RetainInstitutionIdentity = 1 << 3,");
            sb.AppendLine("        /// <summary>Retain Patient Characteristics Option.</summary>");
            sb.AppendLine("        RetainPatientCharacteristics = 1 << 4,");
            sb.AppendLine("        /// <summary>Retain Longitudinal Temporal Information Full Dates Option.</summary>");
            sb.AppendLine("        RetainLongitudinalFullDates = 1 << 5,");
            sb.AppendLine("        /// <summary>Retain Longitudinal Temporal Information Modified Dates Option.</summary>");
            sb.AppendLine("        RetainLongitudinalModifiedDates = 1 << 6,");
            sb.AppendLine("        /// <summary>Clean Descriptors Option.</summary>");
            sb.AppendLine("        CleanDescriptors = 1 << 7,");
            sb.AppendLine("        /// <summary>Clean Structured Content Option.</summary>");
            sb.AppendLine("        CleanStructuredContent = 1 << 8,");
            sb.AppendLine("        /// <summary>Clean Graphics Option.</summary>");
            sb.AppendLine("        CleanGraphics = 1 << 9");
            sb.AppendLine("    }");
            sb.AppendLine();

            // Generate action entry record
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Entry in the de-identification action table.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    internal readonly record struct DeidentificationActionEntry(");
            sb.AppendLine("        uint TagValue,");
            sb.AppendLine("        DeidentificationAction BasicProfile,");
            sb.AppendLine("        DeidentificationAction? RetainSafePrivate,");
            sb.AppendLine("        DeidentificationAction? RetainUIDs,");
            sb.AppendLine("        DeidentificationAction? RetainDeviceIdentity,");
            sb.AppendLine("        DeidentificationAction? RetainInstitutionIdentity,");
            sb.AppendLine("        DeidentificationAction? RetainPatientChars,");
            sb.AppendLine("        DeidentificationAction? RetainLongFullDates,");
            sb.AppendLine("        DeidentificationAction? RetainLongModifiedDates,");
            sb.AppendLine("        DeidentificationAction? CleanDescriptors,");
            sb.AppendLine("        DeidentificationAction? CleanStructuredContent,");
            sb.AppendLine("        DeidentificationAction? CleanGraphics);");
            sb.AppendLine();

            // Generate the profiles class
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Generated de-identification profile data from PS3.15 Table E.1-1.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static partial class DeidentificationProfiles");
            sb.AppendLine("    {");

            // Generate the action entries array
            var deduplicatedActions = actions
                .GroupBy(a => ((uint)a.Group << 16) | a.Element)
                .Select(g => g.First())
                .OrderBy(a => a.Group)
                .ThenBy(a => a.Element)
                .ToList();

            sb.AppendLine("        private static readonly DeidentificationActionEntry[] s_entries = new[]");
            sb.AppendLine("        {");

            foreach (var action in deduplicatedActions)
            {
                var tagValue = ((uint)action.Group << 16) | action.Element;
                sb.Append("            new DeidentificationActionEntry(");
                sb.Append("0x");
                sb.Append(tagValue.ToString("X8", CultureInfo.InvariantCulture));
                sb.Append(", ");
                sb.Append(ActionToEnum(action.BasicProfileAction));
                sb.Append(", ");
                sb.Append(ActionToEnumNullable(action.RetainSafePrivateAction));
                sb.Append(", ");
                sb.Append(ActionToEnumNullable(action.RetainUidsAction));
                sb.Append(", ");
                sb.Append(ActionToEnumNullable(action.RetainDeviceIdentityAction));
                sb.Append(", ");
                sb.Append(ActionToEnumNullable(action.RetainInstitutionIdentityAction));
                sb.Append(", ");
                sb.Append(ActionToEnumNullable(action.RetainPatientCharsAction));
                sb.Append(", ");
                sb.Append(ActionToEnumNullable(action.RetainLongFullDatesAction));
                sb.Append(", ");
                sb.Append(ActionToEnumNullable(action.RetainLongModifiedDatesAction));
                sb.Append(", ");
                sb.Append(ActionToEnumNullable(action.CleanDescriptorsAction));
                sb.Append(", ");
                sb.Append(ActionToEnumNullable(action.CleanStructuredContentAction));
                sb.Append(", ");
                sb.Append(ActionToEnumNullable(action.CleanGraphicsAction));
                sb.AppendLine("),");
            }

            sb.AppendLine("        };");
            sb.AppendLine();

            // Generate lookup dictionary
            sb.AppendLine("#if NET8_0_OR_GREATER");
            sb.AppendLine("        private static readonly FrozenDictionary<uint, DeidentificationActionEntry> s_byTag =");
            sb.AppendLine("            s_entries.ToFrozenDictionary(e => e.TagValue);");
            sb.AppendLine("#else");
            sb.AppendLine("        private static readonly Dictionary<uint, DeidentificationActionEntry> s_byTag =");
            sb.AppendLine("            new Dictionary<uint, DeidentificationActionEntry>();");
            sb.AppendLine();
            sb.AppendLine("        static DeidentificationProfiles()");
            sb.AppendLine("        {");
            sb.AppendLine("            foreach (var entry in s_entries)");
            sb.AppendLine("            {");
            sb.AppendLine("                s_byTag[entry.TagValue] = entry;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("#endif");
            sb.AppendLine();

            // Generate count property
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Gets the number of tags with defined de-identification actions.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        public static int Count => {deduplicatedActions.Count};");
            sb.AppendLine();

            // Generate GetAction method
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Gets the de-identification action for a tag.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <param name=\"tag\">The DICOM tag.</param>");
            sb.AppendLine("        /// <param name=\"options\">Profile options to apply.</param>");
            sb.AppendLine("        /// <returns>The action to apply, or Remove for unknown tags.</returns>");
            sb.AppendLine("        public static DeidentificationAction GetAction(DicomTag tag, DeidentificationProfileOption options = DeidentificationProfileOption.None)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (!s_byTag.TryGetValue(tag.Value, out var entry))");
            sb.AppendLine("            {");
            sb.AppendLine("                return DeidentificationAction.Remove; // Unknown tags removed by default");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            // Check options in order - first matching option wins");
            sb.AppendLine("            if ((options & DeidentificationProfileOption.RetainSafePrivate) != 0 && entry.RetainSafePrivate.HasValue)");
            sb.AppendLine("                return entry.RetainSafePrivate.Value;");
            sb.AppendLine("            if ((options & DeidentificationProfileOption.RetainUIDs) != 0 && entry.RetainUIDs.HasValue)");
            sb.AppendLine("                return entry.RetainUIDs.Value;");
            sb.AppendLine("            if ((options & DeidentificationProfileOption.RetainDeviceIdentity) != 0 && entry.RetainDeviceIdentity.HasValue)");
            sb.AppendLine("                return entry.RetainDeviceIdentity.Value;");
            sb.AppendLine("            if ((options & DeidentificationProfileOption.RetainInstitutionIdentity) != 0 && entry.RetainInstitutionIdentity.HasValue)");
            sb.AppendLine("                return entry.RetainInstitutionIdentity.Value;");
            sb.AppendLine("            if ((options & DeidentificationProfileOption.RetainPatientCharacteristics) != 0 && entry.RetainPatientChars.HasValue)");
            sb.AppendLine("                return entry.RetainPatientChars.Value;");
            sb.AppendLine("            if ((options & DeidentificationProfileOption.RetainLongitudinalFullDates) != 0 && entry.RetainLongFullDates.HasValue)");
            sb.AppendLine("                return entry.RetainLongFullDates.Value;");
            sb.AppendLine("            if ((options & DeidentificationProfileOption.RetainLongitudinalModifiedDates) != 0 && entry.RetainLongModifiedDates.HasValue)");
            sb.AppendLine("                return entry.RetainLongModifiedDates.Value;");
            sb.AppendLine("            if ((options & DeidentificationProfileOption.CleanDescriptors) != 0 && entry.CleanDescriptors.HasValue)");
            sb.AppendLine("                return entry.CleanDescriptors.Value;");
            sb.AppendLine("            if ((options & DeidentificationProfileOption.CleanStructuredContent) != 0 && entry.CleanStructuredContent.HasValue)");
            sb.AppendLine("                return entry.CleanStructuredContent.Value;");
            sb.AppendLine("            if ((options & DeidentificationProfileOption.CleanGraphics) != 0 && entry.CleanGraphics.HasValue)");
            sb.AppendLine("                return entry.CleanGraphics.Value;");
            sb.AppendLine();
            sb.AppendLine("            return entry.BasicProfile;");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Generate TryGetEntry method
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Tries to get the de-identification entry for a tag.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        internal static bool TryGetEntry(DicomTag tag, out DeidentificationActionEntry entry)");
            sb.AppendLine("        {");
            sb.AppendLine("            return s_byTag.TryGetValue(tag.Value, out entry);");
            sb.AppendLine("        }");

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string ActionToEnum(string action)
        {
            return action.ToUpperInvariant() switch
            {
                "D" => "DeidentificationAction.Dummy",
                "Z" => "DeidentificationAction.ZeroOrDummy",
                "X" => "DeidentificationAction.Remove",
                "K" => "DeidentificationAction.Keep",
                "C" => "DeidentificationAction.Clean",
                "U" => "DeidentificationAction.RemapUid",
                "ZD" => "DeidentificationAction.ZeroOrDummyConditional",
                "XZ" => "DeidentificationAction.RemoveOrZeroConditional",
                "XD" => "DeidentificationAction.RemoveOrDummyConditional",
                "XZD" => "DeidentificationAction.RemoveOrZeroOrDummyConditional",
                "XZU" => "DeidentificationAction.RemoveOrZeroOrUidConditional",
                _ => "DeidentificationAction.Remove"
            };
        }

        private static string ActionToEnumNullable(string action)
        {
            if (string.IsNullOrEmpty(action))
            {
                return "null";
            }

            return ActionToEnum(action);
        }
    }
}
