using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;

namespace SharpDicom.Generators.Emitters
{
    /// <summary>
    /// Generates C# source code for DICOM dictionary lookups.
    /// </summary>
    internal static class DictionaryEmitter
    {
        /// <summary>
        /// Emits C# source code for DicomDictionary.Generated.cs containing lookup tables.
        /// </summary>
        /// <param name="tags">The tag definitions.</param>
        /// <param name="uids">The UID definitions.</param>
        /// <returns>Generated C# source code.</returns>
        public static string Emit(ImmutableArray<Parsing.TagDefinition> tags, ImmutableArray<Parsing.UidDefinition> uids)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("#if NET8_0_OR_GREATER");
            sb.AppendLine("using System.Collections.Frozen;");
            sb.AppendLine("#endif");
            sb.AppendLine();
            sb.AppendLine("namespace SharpDicom.Data");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Generated DICOM dictionary data - generated from NEMA Part 6 standard XML.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    internal static class GeneratedDictionaryData");
            sb.AppendLine("    {");

            // Generate tag lookup array - dedupe by tag value (group + element)
            // Keep first occurrence (non-retired preferred over retired)
            var deduplicatedTags = tags
                .OrderBy(t => t.IsRetired) // Non-retired first
                .GroupBy(t => ((uint)t.Group << 16) | t.Element)
                .Select(g => g.First())
                .OrderBy(t => t.Group)
                .ThenBy(t => t.Element);

            sb.AppendLine("        private static readonly DicomTagEntry[] s_tagEntries = new[]");
            sb.AppendLine("        {");

            foreach (var tag in deduplicatedTags)
            {
                sb.Append("            new DicomTagEntry(");
                sb.Append("0x");
                sb.Append(tag.Group.ToString("X4", CultureInfo.InvariantCulture));
                sb.Append(", 0x");
                sb.Append(tag.Element.ToString("X4", CultureInfo.InvariantCulture));
                sb.Append(", \"");
                sb.Append(tag.Keyword);
                sb.Append("\", \"");
                sb.Append(EscapeString(tag.Name));
                sb.Append("\", new[] { ");

                // VRs
                for (int i = 0; i < tag.VRs.Length; i++)
                {
                    if (i > 0) sb.Append(", ");
                    sb.Append('"');
                    sb.Append(tag.VRs[i]);
                    sb.Append('"');
                }

                sb.Append(" }, \"");
                sb.Append(tag.VM);
                sb.Append("\", ");
                sb.Append(tag.IsRetired ? "true" : "false");
                sb.AppendLine("),");
            }

            sb.AppendLine("        };");
            sb.AppendLine();

            // Generate tag lookup dictionary
            sb.AppendLine("#if NET8_0_OR_GREATER");
            sb.AppendLine("        private static readonly FrozenDictionary<uint, DicomTagEntry> s_tagByValue =");
            sb.AppendLine("            s_tagEntries.ToFrozenDictionary(e => ((uint)e.Group << 16) | e.Element);");
            sb.AppendLine();
            sb.AppendLine("        private static readonly FrozenDictionary<string, DicomTagEntry> s_tagByKeyword =");
            sb.AppendLine("            s_tagEntries.ToFrozenDictionary(e => e.Keyword, StringComparer.OrdinalIgnoreCase);");
            sb.AppendLine("#else");
            sb.AppendLine("        private static readonly Dictionary<uint, DicomTagEntry> s_tagByValue =");
            sb.AppendLine("            s_tagEntries.ToDictionary(e => ((uint)e.Group << 16) | e.Element);");
            sb.AppendLine();
            sb.AppendLine("        private static readonly Dictionary<string, DicomTagEntry> s_tagByKeyword =");
            sb.AppendLine("            s_tagEntries.ToDictionary(e => e.Keyword, StringComparer.OrdinalIgnoreCase);");
            sb.AppendLine("#endif");
            sb.AppendLine();

            // Generate UID lookup array - dedupe by UID value
            var deduplicatedUids = uids
                .OrderBy(u => u.IsRetired) // Non-retired first
                .GroupBy(u => u.Value)
                .Select(g => g.First())
                .OrderBy(u => u.Value);

            sb.AppendLine("        private static readonly DicomUIDEntry[] s_uidEntries = new[]");
            sb.AppendLine("        {");

            foreach (var uid in deduplicatedUids)
            {
                sb.Append("            new DicomUIDEntry(\"");
                sb.Append(uid.Value);
                sb.Append("\", \"");
                sb.Append(uid.Keyword);
                sb.Append("\", \"");
                sb.Append(EscapeString(uid.Name));
                sb.Append("\", \"");
                sb.Append(uid.Type);
                sb.Append("\", ");
                sb.Append(uid.IsRetired ? "true" : "false");
                sb.AppendLine("),");
            }

            sb.AppendLine("        };");
            sb.AppendLine();

            // Generate UID lookup dictionary
            sb.AppendLine("#if NET8_0_OR_GREATER");
            sb.AppendLine("        private static readonly FrozenDictionary<string, DicomUIDEntry> s_uidByValue =");
            sb.AppendLine("            s_uidEntries.ToFrozenDictionary(e => e.Value);");
            sb.AppendLine();
            sb.AppendLine("        private static readonly FrozenDictionary<string, DicomUIDEntry> s_uidByKeyword =");
            sb.AppendLine("            s_uidEntries.ToFrozenDictionary(e => e.Keyword);");
            sb.AppendLine("#else");
            sb.AppendLine("        private static readonly Dictionary<string, DicomUIDEntry> s_uidByValue =");
            sb.AppendLine("            s_uidEntries.ToDictionary(e => e.Value);");
            sb.AppendLine();
            sb.AppendLine("        private static readonly Dictionary<string, DicomUIDEntry> s_uidByKeyword =");
            sb.AppendLine("            s_uidEntries.ToDictionary(e => e.Keyword);");
            sb.AppendLine("#endif");
            sb.AppendLine();

            // Generate lookup methods
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Looks up a tag entry by group and element.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static DicomTagEntry? GetTag(ushort group, ushort element)");
            sb.AppendLine("        {");
            sb.AppendLine("            var value = ((uint)group << 16) | element;");
            sb.AppendLine("            return s_tagByValue.TryGetValue(value, out var entry) ? entry : null;");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Looks up a tag entry by keyword.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static DicomTagEntry? GetTag(string keyword)");
            sb.AppendLine("        {");
            sb.AppendLine("            return s_tagByKeyword.TryGetValue(keyword, out var entry) ? entry : null;");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Looks up a UID entry by value.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static DicomUIDEntry? GetUID(string value)");
            sb.AppendLine("        {");
            sb.AppendLine("            return s_uidByValue.TryGetValue(value, out var entry) ? entry : null;");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Looks up a UID entry by keyword.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static DicomUIDEntry? GetUIDByKeyword(string keyword)");
            sb.AppendLine("        {");
            sb.AppendLine("            return s_uidByKeyword.TryGetValue(keyword, out var entry) ? entry : null;");
            sb.AppendLine("        }");

            sb.AppendLine("    }");
            sb.AppendLine();

            // Generate entry record types
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Represents a DICOM tag dictionary entry.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public readonly record struct DicomTagEntry(");
            sb.AppendLine("        ushort Group,");
            sb.AppendLine("        ushort Element,");
            sb.AppendLine("        string Keyword,");
            sb.AppendLine("        string Name,");
            sb.AppendLine("        string[] VRs,");
            sb.AppendLine("        string VM,");
            sb.AppendLine("        bool IsRetired);");
            sb.AppendLine();

            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Represents a DICOM UID dictionary entry.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public readonly record struct DicomUIDEntry(");
            sb.AppendLine("        string Value,");
            sb.AppendLine("        string Keyword,");
            sb.AppendLine("        string Name,");
            sb.AppendLine("        string Type,");
            sb.AppendLine("        bool IsRetired);");

            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string EscapeString(string text)
        {
            if (string.IsNullOrEmpty(text))
            {
                return text;
            }

            return text
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\r", "\\r")
                .Replace("\n", "\\n");
        }
    }
}
