using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace SharpDicom.Generators.Emitters
{
    /// <summary>
    /// Generates C# source code for DicomTag dictionary.
    /// </summary>
    internal static class TagEmitter
    {
        /// <summary>
        /// Emits C# source code for DicomTag.Generated.cs containing static tag members
        /// and lookup dictionaries.
        /// </summary>
        /// <param name="tags">The tag definitions to emit.</param>
        /// <returns>Generated C# source code.</returns>
        public static string Emit(ImmutableArray<Parsing.TagDefinition> tags)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("namespace SharpDicom.Data");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// DICOM tag dictionary - generated from NEMA Part 6 standard XML.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static partial class DicomTags");
            sb.AppendLine("    {");

            // Sort tags by group/element for logical organization
            var sortedTags = tags.OrderBy(t => t.Group).ThenBy(t => t.Element).ToList();

            // Track current group for section comments
            ushort lastGroup = 0xFFFF;

            foreach (var tag in sortedTags)
            {
                // Add group section comments
                if (tag.Group != lastGroup)
                {
                    if (lastGroup != 0xFFFF)
                    {
                        sb.AppendLine();
                    }
                    sb.AppendLine($"        // Group {tag.Group:X4}");
                    lastGroup = tag.Group;
                }

                // Build XML doc comment
                sb.AppendLine("        /// <summary>");
                sb.Append("        /// ");
                sb.Append(EscapeXmlComment(tag.Name));
                sb.Append(" (");
                sb.Append(tag.Group.ToString("X4"));
                sb.Append(",");
                sb.Append(tag.Element.ToString("X4"));
                sb.Append(") - ");
                sb.Append(string.Join("/", tag.VRs));
                sb.Append(" - VM:");
                sb.Append(tag.VM);
                if (tag.IsRetired)
                {
                    sb.Append(" [RETIRED]");
                }
                sb.AppendLine();
                sb.AppendLine("        /// </summary>");

                // Add Obsolete attribute for retired tags
                if (tag.IsRetired)
                {
                    sb.AppendLine("        [System.Obsolete(\"This tag is retired in the DICOM standard.\")]");
                }

                // Generate static readonly field
                sb.Append("        public static readonly DicomTag ");
                sb.Append(tag.Keyword);
                sb.Append(" = new DicomTag(0x");
                sb.Append(tag.Group.ToString("X4"));
                sb.Append(", 0x");
                sb.Append(tag.Element.ToString("X4"));
                sb.AppendLine(");");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string EscapeXmlComment(string text)
        {
            if (string.IsNullOrEmpty(text))
            {
                return text;
            }

            return text
                .Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;")
                .Replace("\"", "&quot;");
        }
    }
}
