using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace SharpDicom.Generators.Emitters
{
    /// <summary>
    /// Generates C# source code for TransferSyntax definitions.
    /// </summary>
    internal static class TransferSyntaxEmitter
    {
        /// <summary>
        /// Emits C# source code for TransferSyntax.Generated.cs containing transfer syntax definitions.
        /// </summary>
        /// <param name="transferSyntaxUids">The UID definitions for transfer syntaxes.</param>
        /// <returns>Generated C# source code.</returns>
        public static string Emit(ImmutableArray<Parsing.UidDefinition> transferSyntaxUids)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("namespace SharpDicom.Data");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// DICOM transfer syntax definitions - generated from NEMA Part 6 standard XML.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static partial class TransferSyntaxes");
            sb.AppendLine("    {");

            foreach (var uid in transferSyntaxUids.OrderBy(u => u.Value))
            {
                // Build XML doc comment
                sb.AppendLine("        /// <summary>");
                sb.Append("        /// ");
                sb.Append(EscapeXmlComment(uid.Name));
                if (uid.IsRetired)
                {
                    sb.Append(" [RETIRED]");
                }
                sb.AppendLine();
                sb.AppendLine("        /// </summary>");

                // Add Obsolete attribute for retired transfer syntaxes
                if (uid.IsRetired)
                {
                    sb.AppendLine("        [System.Obsolete(\"This transfer syntax is retired in the DICOM standard.\")]");
                }

                // Generate static readonly field
                sb.Append("        public static readonly DicomUID ");
                sb.Append(uid.Keyword);
                sb.Append(" = DicomUIDs.");
                sb.Append(uid.Keyword);
                sb.AppendLine(";");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string EscapeXmlComment(string text)
        {
            if (string.IsNullOrEmpty(text))
            {
                return text;
            }

            return text
                .Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;")
                .Replace("\"", "&quot;");
        }
    }
}
