using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace SharpDicom.Generators.Emitters
{
    /// <summary>
    /// Generates C# source code for DicomUID dictionary.
    /// </summary>
    internal static class UidEmitter
    {
        /// <summary>
        /// Emits C# source code for DicomUID.Generated.cs containing static UID members
        /// and lookup dictionaries.
        /// </summary>
        /// <param name="uids">The UID definitions to emit.</param>
        /// <returns>Generated C# source code.</returns>
        public static string Emit(ImmutableArray<Parsing.UidDefinition> uids)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("namespace SharpDicom.Data");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// DICOM UID dictionary - generated from NEMA Part 6 standard XML.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static partial class DicomUIDs");
            sb.AppendLine("    {");

            // Group UIDs by type for better organization
            var sortedUids = uids
                .OrderBy(u => u.Type)
                .ThenBy(u => u.Value)
                .ToList();

            string lastType = string.Empty;

            foreach (var uid in sortedUids)
            {
                // Add type section comments
                if (uid.Type != lastType)
                {
                    if (!string.IsNullOrEmpty(lastType))
                    {
                        sb.AppendLine();
                    }
                    sb.AppendLine($"        // {uid.Type}");
                    lastType = uid.Type;
                }

                // Build XML doc comment
                sb.AppendLine("        /// <summary>");
                sb.Append("        /// ");
                sb.Append(EscapeXmlComment(uid.Name));
                sb.Append(" - ");
                sb.Append(uid.Type);
                if (uid.IsRetired)
                {
                    sb.Append(" [RETIRED]");
                }
                sb.AppendLine();
                sb.AppendLine("        /// </summary>");

                // Add Obsolete attribute for retired UIDs
                if (uid.IsRetired)
                {
                    sb.AppendLine("        [System.Obsolete(\"This UID is retired in the DICOM standard.\")]");
                }

                // Generate static readonly field
                sb.Append("        public static readonly DicomUID ");
                sb.Append(uid.Keyword);
                sb.Append(" = new DicomUID(\"");
                sb.Append(uid.Value);
                sb.AppendLine("\");");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string EscapeXmlComment(string text)
        {
            if (string.IsNullOrEmpty(text))
            {
                return text;
            }

            return text
                .Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;")
                .Replace("\"", "&quot;");
        }
    }
}
